<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<title>crusadehimalaya.com Site Map - Generated by www.xml-sitemaps.com</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
	<style type="text/css">
	body {
		background-color: #fff;
		font-family: "Roboto", "Helvetica", "Arial", sans-serif;
		margin: 0;
	}

	#top {

		background-color: #b1d1e8;
		font-size: 16px;
		padding-bottom: 40px;
	}

	nav {
		font-size: 24px;

		margin: 0px 30px 0px;
		border-bottom-left-radius: 6px;
		border-bottom-right-radius: 6px;
		background-color: #f3f3f3;
		color: #666;
		box-shadow: 0 10px 20px -12px rgba(0, 0, 0, 0.42), 0 3px 20px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
		padding: 10px 0;
		text-align: center;
		z-index: 1;
	}

	h3 {
		margin: auto;
		padding: 10px;
		max-width: 600px;
		color: #666;
	}

	h3 span {
		float: right;
	}

	h3 a {
		font-weight: normal;
		display: block;
	}


	#cont {
		position: relative;
		border-radius: 6px;
		box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);

		background: #f3f3f3;

		margin: -20px 30px 0px 30px;
		padding: 20px;
	}

	a:link,
	a:visited {
		color: #0180AF;
		text-decoration: underline;
	}

	a:hover {
		color: #666;
	}


	#footer {
		padding: 10px;
		text-align: center;
	}

	ul {
    	margin: 0px;

    	padding: 0px;
    	list-style: none;
	}
	li {
		margin: 0px;
	}
	li ul {
		margin-left: 20px;
	}

	.lhead {
		background: #ddd;
		padding: 10px;
    	margin: 10px 0px;
	}

	.lcount {
		padding: 0px 10px;
	}

	.lpage {
		border-bottom: #ddd 1px solid;
		padding: 5px;
	}
	.last-page {
		border: none;
	}
	</style>
</head>

<body>
	<div id="top">
		<nav>crusadehimalaya.com HTML Site Map</nav>
		<h3>
<span>Last updated: 2019, June 12<br />
Total pages: 68</span>
<a href="https://crusadehimalaya.com">crusadehimalaya.com Homepage</a>
</h3></div>
	<div id="cont">
		<ul class="level-0">

            <li class="lhead">/  <span class="lcount">10 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/" title="Crusade Himalaya | Empower, Educate, Encourage">Crusade Himalaya | Empower, Educate, Encourage</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/whats-on" title="What's On This Month | Crusade Himalaya
">What's On This Month | Crusade Himalaya
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/who-we-are" title="Crusade Himalaya | Empower, Educate, Encourage">Crusade Himalaya | Empower, Educate, Encourage</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-blog" title="Crusade Himalaya | Empower, Educate, Encourage">Crusade Himalaya | Empower, Educate, Encourage</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/contact" title="Contact | Crusade Himalaya
">Contact | Crusade Himalaya
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/terms-and-conditions" title="Terms and Conditions | Crusade Himalaya
">Terms and Conditions | Crusade Himalaya
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/privacy-policy" title="Privacy Policy | Crusade Himalaya
">Privacy Policy | Crusade Himalaya
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/link-exchange" title="Link Exchange | Crusade Himalaya
">Link Exchange | Crusade Himalaya
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/press" title="Press | Crusade Himalaya
">Press | Crusade Himalaya
</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/sitemap" title="crusadehimalaya.com Site Map">crusadehimalaya.com Site Map</a></li><li><ul class="level-1">

            <li class="lhead">destination/  <span class="lcount">6 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/destination/everest-region" title="Destination|Everest Region
">Destination|Everest Region
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/annapurna-region" title="Destination|Annapurna Region
">Destination|Annapurna Region
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/manaslu-region" title="Destination|Manaslu Region
">Destination|Manaslu Region
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/langtang-region" title="Destination|Langtang Region
">Destination|Langtang Region
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/mustang-region" title="Destination|Mustang Region
">Destination|Mustang Region
</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/off-beaten-path" title="Destination|Off Beaten Path
">Destination|Off Beaten Path
</a></li><li><ul class="level-2">

            <li class="lhead">annapurna-region/  <span class="lcount">3 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/destination/annapurna-region/trekking" title="Trekking | Annapurna Region">Trekking | Annapurna Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/annapurna-region/climbing" title="Climbing | Annapurna Region">Climbing | Annapurna Region</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/annapurna-region/heli-tour" title="Heli Tour | Annapurna Region">Heli Tour | Annapurna Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">everest-region/  <span class="lcount">3 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/destination/everest-region/trekking" title="Trekking | Everest Region">Trekking | Everest Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/destination/everest-region/climbing" title="Climbing | Everest Region">Climbing | Everest Region</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/everest-region/heli-tour" title="Heli Tour | Everest Region">Heli Tour | Everest Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">langtang-region/  <span class="lcount">1 pages</span></li>
            
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/langtang-region/trekking" title="Trekking | Langtang Region">Trekking | Langtang Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">manaslu-region/  <span class="lcount">1 pages</span></li>
            
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/manaslu-region/trekking" title="Trekking | Manaslu Region">Trekking | Manaslu Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">mustang-region/  <span class="lcount">1 pages</span></li>
            
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/mustang-region/trekking" title="Trekking | Mustang Region">Trekking | Mustang Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">off-beaten-path/  <span class="lcount">1 pages</span></li>
            
<li class="lpage last-page"><a href="https://crusadehimalaya.com/destination/off-beaten-path/trekking" title="Trekking | Off Beaten Path">Trekking | Off Beaten Path</a></li>
</ul></li>
</ul><ul class="level-1">

            <li class="lhead">travel-blog/  <span class="lcount">2 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/travel-blog/what-does-om-mani-padme-hum-mean" title="Crusade Himalaya | Empower, Educate, Encourage">Crusade Himalaya | Empower, Educate, Encourage</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/travel-blog/inside-lumbini-exploring-birthplace-of-gautama-buddha-unesco-world-heritage-site" title="Crusade Himalaya | Empower, Educate, Encourage">Crusade Himalaya | Empower, Educate, Encourage</a></li>
</ul><ul class="level-1">

            <li class="lhead">travel-style/  <span class="lcount">3 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking" title="Travel Style | Trekking in Nepal
">Travel Style | Trekking in Nepal
</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/climbing" title="Travel Style | Climbing in Nepal
">Travel Style | Climbing in Nepal
</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/travel-style/heli-tour" title="Travel Style | Heli Tour in Nepal
">Travel Style | Heli Tour in Nepal
</a></li><li><ul class="level-2">

            <li class="lhead">climbing/  <span class="lcount">2 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/climbing/everest-region" title="Climbing in Everest Region">Climbing in Everest Region</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/travel-style/climbing/annapurna-region" title="Climbing in Annapurna Region">Climbing in Annapurna Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">heli-tour/  <span class="lcount">2 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/heli-tour/everest-region" title="Heli Tour in Everest Region">Heli Tour in Everest Region</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/travel-style/heli-tour/annapurna-region" title="Heli Tour in Annapurna Region">Heli Tour in Annapurna Region</a></li>
</ul><ul class="level-2">

            <li class="lhead">trekking/  <span class="lcount">6 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking/everest-region" title="Trekking in Everest Region">Trekking in Everest Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking/annapurna-region" title="Trekking in Annapurna Region">Trekking in Annapurna Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking/manaslu-region" title="Trekking in Manaslu Region">Trekking in Manaslu Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking/langtang-region" title="Trekking in Langtang Region">Trekking in Langtang Region</a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/travel-style/trekking/off-beaten-path" title="Trekking in Off Beaten Path">Trekking in Off Beaten Path</a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/travel-style/trekking/mustang-region" title="Trekking in Mustang Region">Trekking in Mustang Region</a></li>
</ul></li>
</ul><ul class="level-1">

            <li class="lhead">trip/  <span class="lcount">27 pages</span></li>
            
<li class="lpage"><a href="https://crusadehimalaya.com/trip/everest-base-camp-trek" title="Everest Base Camp Trek | 14  Days ">Everest Base Camp Trek | 14  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/annapurna-base-camp-trek" title="Annapurna Base Camp Trek | 15  Days ">Annapurna Base Camp Trek | 15  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/annapurna-circuit-trek" title="Annapurna Circuit Trek | 19  Days ">Annapurna Circuit Trek | 19  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/tsum-valley-trek" title="Tsum Valley Trek | 19  Days ">Tsum Valley Trek | 19  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/langtang-valley-trek" title="Langtang Valley Trek | 11  Days ">Langtang Valley Trek | 11  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/everest-three-passes-trek" title="Everest Three Passes Trek | 20  Days ">Everest Three Passes Trek | 20  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/gokyo-lake-trek" title="Gokyo Lake Trek | 14  Days ">Gokyo Lake Trek | 14  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/everest-base-camp-trek-via-jiri" title="Everest Base Camp Trek via Jiri | 21  Days ">Everest Base Camp Trek via Jiri | 21  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/mardi-himal-trek" title="Mardi Himal Trek | 11  Days ">Mardi Himal Trek | 11  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/nar-phu-valley-trek" title="Nar Phu Valley Trek | 19  Days ">Nar Phu Valley Trek | 19  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/tamang-heritage-trek" title="Tamang Heritage Trek | 14  Days ">Tamang Heritage Trek | 14  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/upper-mustang-trek" title="Upper Mustang Trek | 16  Days ">Upper Mustang Trek | 16  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/mustang-tiji-festival-trek" title="Mustang Tiji Festival Trek | 18  Days ">Mustang Tiji Festival Trek | 18  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/tilicho-lake-trek" title="Tilicho Lake Trek | 17  Days ">Tilicho Lake Trek | 17  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/ski-in-annapurna-base-camp" title="Ski in Annapurna Base Camp | 15  Days ">Ski in Annapurna Base Camp | 15  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/annapurna-mountain-biking" title="Annapurna Mountain Biking | 13  Days ">Annapurna Mountain Biking | 13  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/kathmandu-valley-tour" title="Kathmandu Valley Tour | 1  Day ">Kathmandu Valley Tour | 1  Day </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/manaslu-circuit-trek" title="Manaslu Circuit Trek | 18  Days ">Manaslu Circuit Trek | 18  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/langtang-gosainkunda-trek" title="Langtang Gosainkunda trek | 14  Days ">Langtang Gosainkunda trek | 14  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/ruby-valley-trek" title="Ruby Valley Trek | 13  Days ">Ruby Valley Trek | 13  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/mera-peak-climbing" title="Mera Peak Climbing | 19  Days ">Mera Peak Climbing | 19  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/island-peak-climbing" title="Island peak climbing | 17  Days ">Island peak climbing | 17  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/lobuche-peak-climbing" title="Lobuche Peak Climbing | 18  Days ">Lobuche Peak Climbing | 18  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/tent-peak-climbing" title="Tent Peak Climbing | 18  Days ">Tent Peak Climbing | 18  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/luxury-everest-base-camp-helicopter-tour" title="Luxury Everest Base Camp Helicopter Tour | 4  Days ">Luxury Everest Base Camp Helicopter Tour | 4  Days </a></li>
<li class="lpage"><a href="https://crusadehimalaya.com/trip/luxury-annapurna-base-camp-helicopter-tour" title="Luxury Annapurna Base Camp Helicopter Tour | 5  Days ">Luxury Annapurna Base Camp Helicopter Tour | 5  Days </a></li>
<li class="lpage last-page"><a href="https://crusadehimalaya.com/trip/momo-tour-momo-cooking-class-workshop" title="Momo Tour: Momo Cooking Class Workshop | 1  Day ">Momo Tour: Momo Cooking Class Workshop | 1  Day </a></li>
</ul></li>
</ul>
		<!--
Please note:
You are not allowed to remove the copyright notice below.
Thank you!
www.xml-sitemaps.com
-->
	</div>
</body>

</html>